// @vitest-environment node

import { Buffer } from "node:buffer";
import { PublicKey } from "@solana/web3.js";
import { describe, expect, it } from "vitest";

import {
  FREEZE_DISCRIMINATOR,
  INITIALIZE_OFFERING_DISCRIMINATOR,
  OFFERING_ACCOUNT_DISCRIMINATOR,
  SETTLE_PURCHASE_DISCRIMINATOR,
  SET_ELIGIBILITY_DISCRIMINATOR,
  THAW_DISCRIMINATOR,
  TOKEN_2022_PROGRAM_ID,
  buildFreezeInstruction,
  buildThawInstruction,
  decodeOffering,
  deriveEligibilityPda,
  deriveOfferingPda,
} from "./dvp";

function key(byte: number): PublicKey {
  return new PublicKey(new Uint8Array(32).fill(byte));
}

function u64(value: bigint): Buffer {
  const data = Buffer.alloc(8);
  data.writeBigUInt64LE(value);
  return data;
}

describe("Quasar DvP client ABI", () => {
  it("uses the one-byte discriminators generated by Quasar", () => {
    expect(Array.from(INITIALIZE_OFFERING_DISCRIMINATOR)).toEqual([0]);
    expect(Array.from(SETTLE_PURCHASE_DISCRIMINATOR)).toEqual([1]);
    expect(Array.from(SET_ELIGIBILITY_DISCRIMINATOR)).toEqual([2]);
    expect(Array.from(THAW_DISCRIMINATOR)).toEqual([3]);
    expect(Array.from(FREEZE_DISCRIMINATOR)).toEqual([4]);
    expect(Array.from(OFFERING_ACCOUNT_DISCRIMINATOR)).toEqual([1]);
  });

  it("decodes Offering data after the Quasar account discriminator", () => {
    const authority = key(1);
    const propertyMint = key(2);
    const usdcMint = key(3);
    const treasury = key(4);
    const vault = key(5);
    const data = Buffer.concat([
      OFFERING_ACCOUNT_DISCRIMINATOR,
      authority.toBuffer(),
      propertyMint.toBuffer(),
      usdcMint.toBuffer(),
      treasury.toBuffer(),
      vault.toBuffer(),
      u64(50_000_000n),
      u64(1_000n),
      u64(10n),
      Buffer.from([249, 1]),
    ]);

    expect(decodeOffering(data)).toEqual({
      authority,
      propertyMint,
      usdcMint,
      treasury,
      vault,
      pricePerToken: 50_000_000n,
      totalOffering: 1_000n,
      sold: 10n,
      bump: 249,
      closed: true,
    });
  });

  it("rejects non-Offering account data before decoding fields", () => {
    const data = Buffer.concat([
      Buffer.from([2]),
      Buffer.alloc(32 * 5 + 8 * 3 + 2),
    ]);

    expect(() => decodeOffering(data)).toThrow("Not an Offering account");
  });

  it("builds thaw with the explicit owner account before eligibility", () => {
    const cranker = key(6);
    const propertyMint = key(7);
    const tokenAccount = key(8);
    const owner = key(9);
    const [offering] = deriveOfferingPda(propertyMint);
    const [eligibility] = deriveEligibilityPda(propertyMint, owner);

    const ix = buildThawInstruction({
      cranker,
      propertyMint,
      tokenAccount,
      owner,
      tokenProgram: TOKEN_2022_PROGRAM_ID,
    });

    expect(Array.from(ix.data)).toEqual([3]);
    expect(ix.keys).toHaveLength(7);
    expect(ix.keys[0]).toMatchObject({ pubkey: cranker, isSigner: true, isWritable: true });
    expect(ix.keys[1]).toMatchObject({ pubkey: offering, isSigner: false, isWritable: false });
    expect(ix.keys[2]).toMatchObject({ pubkey: propertyMint, isSigner: false, isWritable: false });
    expect(ix.keys[3]).toMatchObject({ pubkey: tokenAccount, isSigner: false, isWritable: true });
    expect(ix.keys[4]).toMatchObject({ pubkey: owner, isSigner: false, isWritable: false });
    expect(ix.keys[5]).toMatchObject({ pubkey: eligibility, isSigner: false, isWritable: false });
    expect(ix.keys[6]).toMatchObject({ pubkey: TOKEN_2022_PROGRAM_ID, isSigner: false, isWritable: false });
  });

  it("builds freeze with the generated Quasar account order", () => {
    const authority = key(10);
    const propertyMint = key(11);
    const tokenAccount = key(12);
    const [offering] = deriveOfferingPda(propertyMint);

    const ix = buildFreezeInstruction({
      authority,
      propertyMint,
      tokenAccount,
    });

    expect(Array.from(ix.data)).toEqual([4]);
    expect(ix.keys).toEqual([
      { pubkey: authority, isSigner: true, isWritable: false },
      { pubkey: offering, isSigner: false, isWritable: false },
      { pubkey: propertyMint, isSigner: false, isWritable: false },
      { pubkey: tokenAccount, isSigner: false, isWritable: true },
      { pubkey: TOKEN_2022_PROGRAM_ID, isSigner: false, isWritable: false },
    ]);
  });
});
