#!/usr/bin/env python3
"""rdx-setup sync-codeowners — A3 hybrid CODEOWNERS generator.

Reads `_bmad/rdx/approvers.yaml` (canonical) and writes a CODEOWNERS section
into `.github/CODEOWNERS`, preserving any foreign manual entries outside the
RDX-managed marker block.

Idempotent: re-running the same script against the same approvers.yaml +
existing CODEOWNERS yields a byte-identical file.

Usage:
    python sync_codeowners.py --project-root /path/to/project

Closes:
    T-L8-CAT4-004 — sync-codeowners generates correct .github/CODEOWNERS

Design notes:
- The marker block (BEGIN/END comments) lets uninstall + re-sync find and
  replace only the RDX-managed section. Anything outside the markers is
  preserved verbatim.
- Identity rendering: emails written as-is; @-prefixed handles written as-is
  (CODEOWNERS already requires `@user` / `@org/team` syntax).
- Pattern emission order follows approvers.yaml's `patterns` order — that's
  the canonical contract source, so its order is the natural sort.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover
    print("PyYAML required: pip install pyyaml", file=sys.stderr)
    sys.exit(2)


BEGIN_MARKER = "# >>> RDX-MANAGED — DO NOT EDIT BY HAND >>>"
END_MARKER = "# <<< RDX-MANAGED <<<"
PREAMBLE = (
    "# Generated by `rdx-setup sync-codeowners` from _bmad/rdx/approvers.yaml.\n"
    "# Re-run the command after editing approvers.yaml."
)


def _render_block(approvers: dict) -> str:
    """Render the RDX-managed CODEOWNERS lines (without enclosing markers).

    Each pattern → role lookup → identity list, all space-joined.
    """
    roles = approvers.get("roles") or {}
    patterns = approvers.get("patterns") or []
    lines: list[str] = []
    for entry in patterns:
        role = entry.get("role")
        path = entry.get("path")
        role_def = roles.get(role) or {}
        identities = role_def.get("identities") or []
        if not path or not identities:
            continue
        lines.append(path + " " + " ".join(str(i) for i in identities))
    return "\n".join(lines)


def _strip_existing_managed(current: str) -> str:
    """Remove any prior RDX-managed block (markers inclusive) from `current`."""
    if BEGIN_MARKER not in current:
        return current
    head, _, tail = current.partition(BEGIN_MARKER)
    if END_MARKER not in tail:
        # malformed prior write — drop everything from BEGIN onwards
        return head.rstrip("\n") + "\n"
    _, _, rest = tail.partition(END_MARKER)
    # Consume the marker's trailing newline if present.
    rest = rest.lstrip("\n")
    head = head.rstrip("\n")
    if head and rest:
        return head + "\n\n" + rest
    if head:
        return head + "\n"
    return rest


def sync(project_root: Path) -> int:
    approvers_path = project_root / "_bmad" / "rdx" / "approvers.yaml"
    if not approvers_path.exists():
        print(f"[sync-codeowners] no approvers.yaml at {approvers_path}", file=sys.stderr)
        return 1
    approvers = yaml.safe_load(approvers_path.read_text(encoding="utf-8")) or {}
    block_body = _render_block(approvers)
    codeowners_dir = project_root / ".github"
    codeowners_dir.mkdir(parents=True, exist_ok=True)
    codeowners_path = codeowners_dir / "CODEOWNERS"
    existing = codeowners_path.read_text(encoding="utf-8") if codeowners_path.exists() else ""
    preserved = _strip_existing_managed(existing).rstrip("\n")

    managed = "\n".join([BEGIN_MARKER, PREAMBLE, block_body, END_MARKER])

    if preserved:
        out = preserved + "\n\n" + managed + "\n"
    else:
        out = managed + "\n"
    codeowners_path.write_text(out, encoding="utf-8")
    return 0


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(prog="sync-codeowners")
    p.add_argument("--project-root", default=".", type=Path)
    args = p.parse_args(argv)
    return sync(args.project_root.resolve())


if __name__ == "__main__":
    sys.exit(main())
